// Universal Yahoo-powered NSE/BSE autocomplete for every stock-symbol input
(function(){
const ids=['ssym','isym','ltsym','wadd','psym','csym','fhSym','btSym'];
function attach(input){if(!input||input.dataset.dynamicSearch==='1')return;input.dataset.dynamicSearch='1';input.autocomplete='off';input.placeholder='Search company: Airtel, Reliance, IRCTC…';const wrap=input.parentElement;wrap.style.position='relative';const box=document.createElement('div');box.className='dyn-stock-results';box.style.cssText='display:none;position:absolute;z-index:999;left:0;right:0;top:100%;margin-top:4px;max-height:320px;overflow:auto;background:#0d1b2c;border:1px solid #294766;border-radius:12px;box-shadow:0 14px 34px #0009';wrap.appendChild(box);let timer,ctrl;
async function search(){clearTimeout(timer);let q=input.value.trim();if(q.length<2){box.style.display='none';return}timer=setTimeout(async()=>{try{if(ctrl)ctrl.abort();ctrl=new AbortController();box.style.display='block';box.innerHTML='<div style="padding:12px;color:#92a5bd">Searching NSE/BSE…</div>';let r=await fetch('/api/search?q='+encodeURIComponent(q),{cache:'no-store',signal:ctrl.signal}),j=await r.json();if(!r.ok)throw Error(j.error||'Search failed');let a=(j.results||[]).slice(0,12);box.innerHTML=a.length?a.map(x=>`<div class="dyn-result" data-symbol="${String(x.symbol||'').replace(/"/g,'&quot;')}" style="padding:11px 12px;border-bottom:1px solid #20354e;cursor:pointer"><b>${x.name||x.symbol}</b><br><span style="font-size:12px;color:#92a5bd">${x.symbol} • ${x.exchange||'NSE/BSE'}</span></div>`).join(''):'<div style="padding:12px;color:#92a5bd">No matching NSE/BSE share found.</div>'}catch(e){if(e.name!=='AbortError')box.innerHTML='<div style="padding:12px;color:#ff6577">Search temporarily unavailable</div>'}},250)}
input.addEventListener('input',search);input.addEventListener('focus',()=>{if(input.value.trim().length>=2)search()});box.addEventListener('click',e=>{let row=e.target.closest('.dyn-result');if(!row)return;input.value=row.dataset.symbol;input.dataset.resolvedSymbol=row.dataset.symbol;box.style.display='none';input.dispatchEvent(new Event('change',{bubbles:true}))});document.addEventListener('click',e=>{if(!wrap.contains(e.target))box.style.display='none'})}
function attachMulti(input){if(!input||input.dataset.dynamicMulti==='1')return;input.dataset.dynamicMulti='1';const holder=document.createElement('div');holder.style.cssText='margin-top:7px';const search=document.createElement('input');search.placeholder='Search a company to add…';holder.appendChild(search);input.parentElement.appendChild(holder);attach(search);search.addEventListener('change',()=>{let s=search.value.trim();if(!s)return;let arr=input.value.split(',').map(x=>x.trim()).filter(Boolean);if(!arr.includes(s))arr.push(s);input.value=arr.slice(-30).join(',');search.value=''})}
function scan(){ids.forEach(id=>attach(document.getElementById(id)));attachMulti(document.getElementById('cmpSyms'));attachMulti(document.getElementById('scsyms'));document.querySelectorAll('input').forEach(i=>{let id=(i.id||'').toLowerCase(),ph=(i.placeholder||'').toLowerCase(),lab=i.previousElementSibling?.textContent?.toLowerCase()||'';if((id.includes('sym')||ph.includes('symbol')||lab.includes('symbol'))&&i.type!=='number'&&!['cmpSyms','scsyms'].includes(i.id))attach(i)})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{setTimeout(scan,200);setTimeout(scan,900);setTimeout(scan,1800)});else{setTimeout(scan,100);setTimeout(scan,800)}
})();