// Manjeet Stock Analyzer V8 - confidence meter overlay
(function(){
const $=id=>document.getElementById(id);
function ensureStyles(){const s=document.createElement('style');s.textContent=`
.v8box{margin-top:14px;background:#091727;border:1px solid #20354e;border-radius:14px;padding:14px}.v8title{font-weight:800;margin-bottom:10px}.v8nums{display:flex;justify-content:space-between;gap:10px;font-size:13px;margin-bottom:7px}.v8meter{height:18px;border-radius:99px;background:linear-gradient(90deg,#ff6577 0 35%,#ffc857 35% 65%,#36d17f 65% 100%);position:relative}.v8needle{position:absolute;top:-5px;width:4px;height:28px;background:white;border-radius:3px;box-shadow:0 0 8px #fff;transition:left .45s}.v8score{text-align:center;font-size:22px;font-weight:900;margin-top:9px}.v8comment{margin-top:10px;line-height:1.55;color:#d9e7f7}.v8sub{font-size:11px;color:#92a5bd;margin-top:8px}`;document.head.appendChild(s)}
function mount(p){const why=$(p+'why');if(!why||$(p+'v8'))return;const d=document.createElement('div');d.id=p+'v8';d.className='v8box';d.innerHTML=`<div class="v8title">V8 Market Confidence Meter</div><div class="v8nums"><span>🔴 Bearish <b id="${p}bear">—</b></span><span>🟡 Neutral</span><span>🟢 Bullish <b id="${p}bull">—</b></span></div><div class="v8meter"><span class="v8needle" id="${p}needle" style="left:50%"></span></div><div class="v8score" id="${p}v8score">—</div><div class="v8comment" id="${p}comment">Analyze करने के बाद market analysis यहाँ दिखेगा.</div><div class="v8sub">Confidence is a technical-model score, not a guaranteed probability of future price movement.</div>`;why.parentElement.appendChild(d)}
function update(p,q,L,sup,res,intra,mode){if(!q||!Number.isFinite(q.s))return;/* map signed -100..100 technical score to 0..100 bullish confidence; deliberately compress extremes */let bull=Math.round(Math.max(5,Math.min(95,50+q.s*.42))),bear=100-bull;$(p+'bull').textContent=bull+'%';$(p+'bear').textContent=bear+'%';$(p+'needle').style.left=`calc(${bull}% - 2px)`;let zone=bull>=65?'🟢 Bullish setup':bull<=35?'🔴 Bearish setup':'🟡 Mixed / Neutral';$(p+'v8score').textContent=zone+' • '+bull+'/100';let trend=q.e10>q.e20?'short-term trend positive':'short-term trend weak';let rsi=Number.isFinite(q.R)?(q.R>70?'RSI high/overbought zone में है':q.R>=52?'RSI momentum supportive है':q.R<45?'RSI momentum weak है':'RSI neutral है'):'RSI unavailable';let mac=Number.isFinite(q.M)?(q.M>0?'MACD positive confirmation दे रहा है':'MACD negative confirmation दे रहा है'):'MACD unavailable';let vol=Number.isFinite(q.vr)?(q.vr>1.2?'volume average से मजबूत है':'volume में strong expansion नहीं है'):'volume unavailable';let horizon=intra?`${mode} intraday candles`:(mode==='week'?'1-week swing':'1-month swing');$(p+'comment').innerHTML=`<b>${horizon} analysis:</b> ${trend}; ${rsi}; ${mac}; ${vol}. Current technical support लगभग <b>₹${Number(sup).toLocaleString('en-IN',{maximumFractionDigits:2})}</b> और resistance लगभग <b>₹${Number(res).toLocaleString('en-IN',{maximumFractionDigits:2})}</b> है. ${bull>=65?'Positive setup है, लेकिन resistance और reversal risk देखें.':bull<=35?'Setup weak है; support hold/reversal confirmation महत्वपूर्ण है.':'Signals mixed हैं; stronger breakout/breakdown confirmation का इंतजार useful हो सकता है.'}`}
ensureStyles();function boot(){mount('s');mount('i');if(typeof window.calc!=='function')return;const old=window.calc;window.calc=function(rows,intra,mode){const q=old(rows,intra,mode);q.__rows=rows;q.__intra=intra;q.__mode=mode;return q};const observer=new MutationObserver(()=>{['s','i'].forEach(p=>{const st=$(p+'status');if(!st||!st.classList.contains('ok'))return;try{const rows=window.__lastRows?.[p],q=window.__lastCalc?.[p];if(rows&&q){const rr=rows.slice(-20),sup=Math.min(...rr.map(x=>x.low)),res=Math.max(...rr.map(x=>x.high));update(p,q,rows.at(-1),sup,res,p==='i',$(p+'mode')?.value)}}catch(e){}})});observer.observe(document.body,{subtree:true,childList:true,characterData:true,attributes:true});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
window.ManV8={update};
})();